return {
  { import = "plugins.core" },
  { import = "plugins.completion" },
  { import = "plugins.lsp" },
  { import = "plugins.debug" },
  { import = "plugins.format" },
  { import = "plugins.test" },
  { import = "plugins.treesitter" },
  { import = "plugins.editor" },
  { import = "plugins.search" },
  { import = "plugins.explorer" },
  { import = "plugins.terminal" },
  { import = "plugins.database" },
  { import = "plugins.runner" },
  { import = "plugins.git" },
  { import = "plugins.ui" },
  { import = "plugins.ui.themes" },
  { import = "plugins.ai" },
  { import = "plugins.misc" },
}
